name: Pull Request
description: Propose a new change
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the changes.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - UI (React)
        - Rust (Tauri)
        - Lib
        - Other
    validations:
      required: true
